### PR TITLE
DOC-53 changes

### PR DESCRIPTION
**Pull request by cybsecmaster**

### CODE REVIEW

**Review by MaelDre — APPROVED** [review]
We dont see the logo very well but in my opinion it is not very important. We could improve it in a second step.

image

**Comment by cybsecmaster** [comment]
@MaelDre What do you think about this variant:

image

**Comment by MaelDre** [comment]
yes I prefer the light version.

As I'm not 100% sure there is no any risk to release this new page I prefer wait another review  from @jeromeleonard or @To-om ? and let them merge this PR

**Comment by cybsecmaster** [comment]
Great. Let's wait for their review.

In the meantime, I have pushed the changes that contain the light version.

**Pull request merged**
